---
title: "final_project"
author: "b03801053劉倢如"
date: "2018/1/7"
output: html_document
---


<h3>前言：PM2.5是什麼?為什麼會選擇PM2.5?</h3>
<h5><=2.5um的粒子就是PM2.5，通稱為細懸浮微粒，因為過於微小，因此進入人體後不容易出來，因此會對人體的肺部、心血管產生比較大的傷害</h5>

<h5>每逢秋冬季節，東北季風帶來的境外空氣污染，再加上台灣本土的空氣污染，造成中南部地區多日空氣品質狀況達紅色警戒，而台灣本地的空污的原兇究竟是來自哪裡？</h5>

<h5>從新聞媒體對中部地區居民的訪問得知，火力發電廠就在附近，空氣品質很不好，很擔心#環團也將空汙主因指向中部火力發電廠，因此我們從https://pm25.lass-ne###t.org/zh_tw/ PM2.5開放資料網站爬下了2017年10~12月份的PM2.5資料來看看這三個月的空氣品質狀況</h5>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(leaflet)
library(readxl)
library(dplyr)
library(openair)
library(dygraphs)
library(ggmap)
library(mapproj)
library(maps)
library(ggplot2)
library(plotly)
```

```{r}
wsite<-read_xlsx("whole.xlsx")
d<-data.frame(wsite$ID,wsite$lat,wsite$lon)
d$nID<-substr(d$wsite.ID,9,12)
names(d)<-c("ID","lat","lon","nID")
map <- get_map(location = c(lon = 120.573, lat = 24.266),
               zoom = 11, language = "zh-TW")


ggmap(map, extent = "normal") +
  geom_point(aes(x=d$lon, y=d$lat) ,colour="pink", size=4,data = d)+
  geom_text(data = d,aes(x=lon,y=lat,label=d$nID),size=2.6,colour="firebrick")+
  scale_colour_discrete(l = 45)
  
```


```{r}
dateplot<-function(x){
  fname<-paste0(x,".csv")
  d <- read.csv(fname, header=TRUE)
  d$newdate <- d$date
  d$newtime<- d$time
  d$finaldate<- paste0(d$newdate," ",d$newtime)
  dn <- select(d,gps_lat,gps_lon,s_d0,finaldate)
  tmp <- data.frame(dn$finaldate,dn$s_d0,dn$gps_lat,dn$gps_lon)
  colnames(tmp) <- c("date","pm25","lat","lon")
  tmp$date <- as.POSIXct(strptime(tmp$date, format= "%Y-%m-%d %H:%M:%S", "GMT"))
  return (calendarPlot(tmp,main =  paste("PM2.5 in 2017 from 10~12 month at site",x),key.header="AQI value", digits = 20,pollutant = "pm25",annotate = "date",year = 2017,breaks = c(0,15.4,35.4,54.4,150.4,250.4,350.4), labels = c("0.0 - 15.4","15.5 - 35.4","35.5 - 54.4","54.5 - 150.4","150.5 - 250.4",">=250.5")
                       ,cols = c("Green", "Yellow", "Orange", "Red", "Purple","darkmagenta")))
}
```

```{r}
datetable<-function(x){
  fname<-paste0(x,".csv")
  d <- read.csv(fname, header=TRUE)
  d$newdate <- d$date
  d$newtime<- d$time
  d$finaldate<- paste0(d$newdate," ",d$newtime)
  dn <- select(d,gps_lat,gps_lon,s_d0,finaldate)
  tmp <- data.frame(dn$finaldate,dn$s_d0,dn$gps_lat,dn$gps_lon)
  colnames(tmp) <- c("date","pm25","lat","lon")
  tmp$date <- as.POSIXct(strptime(tmp$date, format= "%Y-%m-%d %H:%M:%S", "GMT"))
  tmp$nmonth<-substr(tmp$date,6,7)
  tmp$ndate<-substr(tmp$date,9,10)
  tmp$nhour<-substr(tmp$date,12,13)

  tmp$nmonth<-as.numeric(tmp$nmonth)
  tmp$nhour<-as.numeric(tmp$nhour)
  tmp$ndate<-as.numeric(tmp$ndate)
  tmp$pm25<-as.numeric(tmp$pm25)
  return(tmp)
}




```

```{r}
distin<-function(x){

for(j in c(10:12)){
cg=0
cy=0
co=0
cr=0
cp=0
cb=0

if(j==10){
for(i in c(1:31)){
 
n<-select(x,pm25,ndate,nmonth)%>%
    filter(nmonth==j & ndate==i)
value <- summarise(n,mean(pm25))
if(value=="NaN"){next}
else{
if (value <= 15.4){
  cg = cg+1
}else if(value<=35.4){
  cy = cy+1
}else if(value<=54.4){
  co = co+1
}else if(value<=150.4){
  cr = cr+1
}else if(value<=250.4)
{   cp = cp+1
}else{
  cb = cb+1
}


  df<-data.frame(cg,cy,co,cr,cp,cb)
}
}
}
else if(j==11){for(i in c(1:30)){
  
  n<-select(x,pm25,ndate,nmonth)%>%
    filter(nmonth==j & ndate==i)
  value <- summarise(n,mean(pm25))
  if(value=="NaN"){next}
  else{
  if (value <= 15.4){
    cg = cg+1
  }else if(value<=35.4){
    cy = cy+1
  }else if(value<=54.4){
    co = co+1
  }else if(value<=150.4){
    cr = cr+1
  }else if(value<=250.4)
  {   cp = cp+1
  }else{
    cb = cb+1
  }
  
}
  df1<-data.frame(cg,cy,co,cr,cp,cb)}  
}
else{
  for(i in c(1:31)){
   
    n<-select(x,pm25,ndate,nmonth)%>%
      filter(nmonth==j & ndate==i)
    value <- summarise(n,mean(pm25))
    if(value=="NaN"){next}
    else{
    if (value <= 15.4){
      cg = cg+1
    }else if(value<=35.4){
      cy = cy+1
    }else if(value<=54.4){
      co = co+1
    }else if(value<=150.4){
      cr = cr+1
    }else if(value<=250.4)
    {   cp = cp+1
    }else{
      cb = cb+1
    }
  
}
  
  df2<-data.frame(cg,cy,co,cr,cp,cb)}  
}
}
new <- rbind(df,df1,df2)

return(new)
}
```


```{r}
name<-function(b){rownames(b) <- c(10,11,12)
colnames(b) <- c("良好","普通","對敏感族群不健康","對所有族群不健康","非常不健康","危害")
return(b)}
```


```{r}
b = distin(datetable("74DA3895C4C8"))
name(b)
dateplot("74DA3895C4C8")


b = distin(datetable("74DA3895C4A6"))
name(b)
dateplot("74DA3895C4A6")


b = distin(datetable("74DA3895C248"))
name(b)
dateplot("74DA3895C248")


b = distin(datetable("74DA3895C4F4"))
name(b)
dateplot("74DA3895C4F4")



b = distin(datetable("74DA3895C4EE"))
name(b)
dateplot("74DA3895C4EE")


b = distin(datetable("74DA3895C4FC"))
name(b)
dateplot("74DA3895C4FC")


b = distin(datetable("74DA3895C4F6"))
name(b)
dateplot("74DA3895C4F6")


b = distin(datetable("74DA3895C25C"))
name(b)
dateplot("74DA3895C25C")


b = distin(datetable("74DA3895C240"))
name(b)
dateplot("74DA3895C240")

b = distin(datetable("74DA3895C246"))
name(b)
dateplot("74DA3895C246")

b = distin(datetable("74DA3895C2A6"))
name(b)
dateplot("74DA3895C2A6")

b = distin(datetable("74DA3895C374"))
name(b)
dateplot("74DA3895C374")

b = distin(datetable("74DA3895C500"))
name(b)
dateplot("74DA3895C500")

b = distin(datetable("74DA3895C24A"))
name(b)
dateplot("74DA3895C24A")

b = distin(datetable("74DA38AF4774"))
name(b)
print(b)
dateplot("74DA38AF4774")

b = distin(datetable("74DA38AF4894"))
name(b)
dateplot("74DA38AF4894")


b = distin(datetable("74DA38B05240"))
name(b)
dateplot("74DA38B05240")

b = distin(datetable("74DA3895C2BA"))
name(b)
dateplot("74DA3895C2BA")

b = distin(datetable("74DA3895C2F2"))
name(b)
dateplot("74DA3895C2F2")

b = distin(datetable("74DA3895C3C2"))
name(b)
dateplot("74DA3895C3C2")

b = distin(datetable("74DA3895C3F0"))
name(b)
dateplot("74DA3895C3F0")

b = distin(datetable("74DA3895C4CE"))
name(b)
dateplot("74DA3895C4CE")

b = distin(datetable("74DA3895C5C6"))
name(b)
dateplot("74DA3895C5C6")

b = distin(datetable("74DA3895C53C"))
name(b)
dateplot("74DA3895C53C")

b = distin(datetable("74DA3895C324"))
name(b)
dateplot("74DA3895C324")

b = distin(datetable("74DA3895C396"))
name(b)
dateplot("74DA3895C396")

b = distin(datetable("74DA3895C454"))
name(b)
dateplot("74DA3895C454")

b = distin(datetable("74DA3895C532"))
name(b)
dateplot("74DA3895C532")

b = distin(datetable("74DA3895C568"))
name(b)
dateplot("74DA3895C568")

b = distin(datetable("74DA3895E0DE"))
name(b)
dateplot("74DA3895E0DE")

b = distin(datetable("74DA3895E0E0"))
name(b)
dateplot("74DA3895E0E0")

b = distin(datetable("74DA38C7CED4"))
name(b)
dateplot("74DA38C7CED4")

b = distin(datetable("74DA3895C262"))
name(b)
dateplot("74DA3895C262")

```
<h5>從日曆圖看出10月份PM2.5濃度達紅色警戒的天數多集中在10號、11號<h5>
<h5>而11月份則是多集中在17號、28號</h5>
<h5>回顧新聞事件，29號是入秋最強一波空污來襲，多處測站則是在28號的時候，就發現空氣品質達紅色警戒</h5>
<h5>比較令人注意的是12月底的空氣品質狀況，從22號開始到月底，幾乎天天都達紅色警戒，受東北季風影響，霾害嚴重</h5>

